name: Update Issue Badge

on:
  issues:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Issue Count
        id: get-issue-count
        run: |
          issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open")
          issue_count=$(echo "$issues" | jq -r 'length')
          echo "::set-output name=issue_count::$issue_count"

      - name: Generate Badge
        run: |
          issue_count=${{ steps.get-issue-count.outputs.issue_count }}

          svg_code="<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"150\" height=\"20\">
            <!-- Your SVG code here -->
            <text x=\"37.5\" y=\"14\" fill=\"#010101\" fill-opacity=\".3\">Open Issues: $issue_count</text>
            <text x=\"37.5\" y=\"13\">Open Issues: $issue_count</text>
          </svg>"

          echo "$svg_code" > issue_badge.svg

      - name: Commit Badge Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add issue_badge.svg
          git commit -m "Update Issue Badge"
          git push origin HEAD:main
